const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_ERROR";
const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";

export { GET_REQUEST, GET_SUCCESS, GET_FAIL,  SIGN_IN, SIGN_OUT}