const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAIL = "GET_ERROR";
const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const ADD_PRODUCT = "ADD_PRODUCT";
const REMOVE_FROM_CART = "PRODUCT_REMOVE_FROM_CART";
const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS"

export { GET_REQUEST, GET_SUCCESS, GET_FAIL,  SIGN_IN, SIGN_OUT, ADD_PRODUCT, REMOVE_FROM_CART, SAVE_SHIPPING_ADDRESS };